#编排文件1：Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloud-native
    namespace: nju17
    labels:
        app: cloud-native
spec:
    replicas: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 30%
            maxUnavailable: 30%
    selector:
        matchLabels:
            app: cloud-native
    template:
        metadata:
            labels:
                app: cloud-native
        spec:
            containers:
                -   image: harbor.edu.cn/nju17/cloud-native-demo:{VERSION}
                    name: cloud-native
                    ports:
                        -   containerPort: 8080
                    resources:
                        requests:
                            cpu: 400m

---

#编排文件2：Service
apiVersion: v1
kind: Service
metadata:
    name: cloud-native-service
    namespace: nju17
    labels:
        app: cloud-native-service
        micrometer-prometheus-discovery: 'true'
spec:
    type: NodePort
    ports:
        -   port: 8080
            targetPort: 8080
            nodePort: 30880
            name: cloud-native-service-port
            protocol: TCP
    selector:
        app: cloud-native

---

#编排文件3：Monitor，实现普罗米修斯功能注册
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: cloud-native-monitor
    namespace: nju17
spec:
    endpoints:
        -   interval: 15s
            path: /actuator/prometheus
            port: cloud-native-service-port
    namespaceSelector:
        any: true
    selector:
        matchLabels:
            micrometer-prometheus-discovery: 'true'